name: Demo to learn githubactions
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
     - name: print greetings
       run: |
          echo "First output"
          echo "Second output"
